### ISSUE TITLE
Network Toggle Problem

### ISSUE THREAD

**Issue by 4PERTURE** [OpenKirin/android_device_huawei_alice#3]
In any ROM I compile, the network toggles (LTE/3G/2G) don't work. Can this be an issue in the tree?

**Comment by Huawei-Dev** [comment]
No, its not à issue about device tree nor vendor blobs,  I'll let you to know soon how you can fix it :)

**Comment by 4PERTURE** [comment]
@Huawei-Dev thank you so much :) another problem i have is when making calls touch screen still works, is there  patch for this?

**Comment by DarkJoker360** [comment]
Hi! There is a workaroung for it, it's the app 'Enable proximity on call' present in the playstore ;)

**Comment by Huawei-Dev** [comment]
you should apply this patch for fixing 2G/3G/LTE network toggle !  https://github.com/Meticulus/android_device_huawei_hi6250/blob/n-emui4/patches/common/frameworks/opt/telephony/0001-telephony-fix-2g-2g-4g-switch.patch

**Comment by 4PERTURE** [comment]
@Huawei-Dev thank you for this surdu, i will give credits in my thread after recompiling. Is there also a patch for the other problem i mentioned? (touch screen still works while making a call)

**Comment by Huawei-Dev** [comment]
No, you should use what @DarkJoker360 already said !

**Comment by ghost** [comment]
@4PERTURE The following fixes that call touch issue for some devices in my code base ...
https://github.com/codeofhonor-dev/android_kernel_huawei_hi6250/commit/f4718a22862b9386f7f12c2c95e917779a73e43d

**Comment by 4PERTURE** [comment]
Thanks @Meticulus, I'll try a new build with that and see how it goes :)
